"""
Auto-generated GUI wrappers for config classes
Generated by: python config.py
"""

from dataclasses import dataclass, field
import tkinter as tk
from core.config import *

@dataclass
class InputConfigGUI:
    """Auto-generated GUI wrapper for InputConfig"""
    _core_config: InputConfig = field(default_factory=InputConfig)

    file_path: tk.StringVar = field(init=False)
    dir_path: tk.StringVar = field(init=False)
    mode: tk.StringVar = field(init=False)
    configuration_file: tk.StringVar = field(init=False)
    length_units: tk.StringVar = field(init=False)
    time_units: tk.StringVar = field(init=False)

    def __post_init__(self):
        self.file_path = tk.StringVar(value=self._core_config.file_path)
        self.dir_path = tk.StringVar(value=self._core_config.dir_path)
        self.mode = tk.StringVar(value=self._core_config.mode)
        self.configuration_file = tk.StringVar(value=self._core_config.configuration_file)
        self.length_units = tk.StringVar(value=self._core_config.length_units)
        self.time_units = tk.StringVar(value=self._core_config.time_units)

    @property
    def config(self) -> InputConfig:
        """Get current config from GUI values"""
        return InputConfig(
            file_path=self.file_path.get(),
            dir_path=self.dir_path.get(),
            mode=self.mode.get(),
            configuration_file=self.configuration_file.get(),
            length_units=self.length_units.get(),
            time_units=self.time_units.get(),
        )

    def update_gui(self, new_config: InputConfig):
        """Update GUI from new config values"""
        self._core_config = new_config
        self.file_path.set(new_config.file_path)
        self.dir_path.set(new_config.dir_path)
        self.mode.set(new_config.mode)
        self.configuration_file.set(new_config.configuration_file)
        self.length_units.set(new_config.length_units)
        self.time_units.set(new_config.time_units)

@dataclass
class ReaderConfigGUI:
    """Auto-generated GUI wrapper for ReaderConfig"""
    _core_config: ReaderConfig = field(default_factory=ReaderConfig)

    accept_dim_channels: tk.BooleanVar = field(init=False)
    accept_dim_images: tk.BooleanVar = field(init=False)
    exposure_time: tk.DoubleVar = field(init=False)
    um_pixel_ratio: tk.DoubleVar = field(init=False)
    verbose: tk.BooleanVar = field(init=False)

    def __post_init__(self):
        self.accept_dim_channels = tk.BooleanVar(value=self._core_config.accept_dim_channels)
        self.accept_dim_images = tk.BooleanVar(value=self._core_config.accept_dim_images)
        self.exposure_time = tk.DoubleVar(value=self._core_config.exposure_time)
        self.um_pixel_ratio = tk.DoubleVar(value=self._core_config.um_pixel_ratio)
        self.verbose = tk.BooleanVar(value=self._core_config.verbose)

    @property
    def config(self) -> ReaderConfig:
        """Get current config from GUI values"""
        return ReaderConfig(
            accept_dim_channels=self.accept_dim_channels.get(),
            accept_dim_images=self.accept_dim_images.get(),
            exposure_time=self.exposure_time.get(),
            um_pixel_ratio=self.um_pixel_ratio.get(),
            verbose=self.verbose.get(),
        )

    def update_gui(self, new_config: ReaderConfig):
        """Update GUI from new config values"""
        self._core_config = new_config
        self.accept_dim_channels.set(new_config.accept_dim_channels)
        self.accept_dim_images.set(new_config.accept_dim_images)
        self.exposure_time.set(new_config.exposure_time)
        self.um_pixel_ratio.set(new_config.um_pixel_ratio)
        self.verbose.set(new_config.verbose)

@dataclass
class WriterConfigGUI:
    """Auto-generated GUI wrapper for WriterConfig"""
    _core_config: WriterConfig = field(default_factory=WriterConfig)

    generate_barcode: tk.BooleanVar = field(init=False)
    save_rds: tk.BooleanVar = field(init=False)
    save_visualizations: tk.BooleanVar = field(init=False)

    def __post_init__(self):
        self.generate_barcode = tk.BooleanVar(value=self._core_config.generate_barcode)
        self.save_rds = tk.BooleanVar(value=self._core_config.save_rds)
        self.save_visualizations = tk.BooleanVar(value=self._core_config.save_visualizations)

    @property
    def config(self) -> WriterConfig:
        """Get current config from GUI values"""
        return WriterConfig(
            generate_barcode=self.generate_barcode.get(),
            save_rds=self.save_rds.get(),
            save_visualizations=self.save_visualizations.get(),
        )

    def update_gui(self, new_config: WriterConfig):
        """Update GUI from new config values"""
        self._core_config = new_config
        self.generate_barcode.set(new_config.generate_barcode)
        self.save_rds.set(new_config.save_rds)
        self.save_visualizations.set(new_config.save_visualizations)

@dataclass
class ChannelConfigGUI:
    """Auto-generated GUI wrapper for ChannelConfig"""
    _core_config: ChannelConfig = field(default_factory=ChannelConfig)

    parse_all_channels: tk.BooleanVar = field(init=False)
    selected_channel: tk.IntVar = field(init=False)

    def __post_init__(self):
        self.parse_all_channels = tk.BooleanVar(value=self._core_config.parse_all_channels)
        self.selected_channel = tk.IntVar(value=self._core_config.selected_channel)

    @property
    def config(self) -> ChannelConfig:
        """Get current config from GUI values"""
        return ChannelConfig(
            parse_all_channels=self.parse_all_channels.get(),
            selected_channel=self.selected_channel.get(),
        )

    def update_gui(self, new_config: ChannelConfig):
        """Update GUI from new config values"""
        self._core_config = new_config
        self.parse_all_channels.set(new_config.parse_all_channels)
        self.selected_channel.set(new_config.selected_channel)

@dataclass
class BinarizationConfigGUI:
    """Auto-generated GUI wrapper for BinarizationConfig"""
    _core_config: BinarizationConfig = field(default_factory=BinarizationConfig)

    threshold_offset: tk.DoubleVar = field(init=False)
    frame_step: tk.IntVar = field(init=False)
    percentage_frames_evaluated: tk.DoubleVar = field(init=False)
    bin_factor: tk.IntVar = field(init=False)
    neighbor_island_fraction: tk.DoubleVar = field(init=False)
    minimum_island_size: tk.IntVar = field(init=False)
    enable_physical_units: tk.BooleanVar = field(init=False)
    invert_binarization: tk.BooleanVar = field(init=False)

    def __post_init__(self):
        self.threshold_offset = tk.DoubleVar(value=self._core_config.threshold_offset)
        self.frame_step = tk.IntVar(value=self._core_config.frame_step)
        self.percentage_frames_evaluated = tk.DoubleVar(value=self._core_config.percentage_frames_evaluated)
        self.bin_factor = tk.IntVar(value=self._core_config.bin_factor)
        self.neighbor_island_fraction = tk.DoubleVar(value=self._core_config.neighbor_island_fraction)
        self.minimum_island_size = tk.IntVar(value=self._core_config.minimum_island_size)
        self.enable_physical_units = tk.BooleanVar(value=self._core_config.enable_physical_units)
        self.invert_binarization = tk.BooleanVar(value=self._core_config.invert_binarization)

    @property
    def config(self) -> BinarizationConfig:
        """Get current config from GUI values"""
        return BinarizationConfig(
            threshold_offset=self.threshold_offset.get(),
            frame_step=self.frame_step.get(),
            percentage_frames_evaluated=self.percentage_frames_evaluated.get(),
            bin_factor=self.bin_factor.get(),
            neighbor_island_fraction=self.neighbor_island_fraction.get(),
            minimum_island_size=self.minimum_island_size.get(),
            enable_physical_units=self.enable_physical_units.get(),
            invert_binarization=self.invert_binarization.get(),
        )

    def update_gui(self, new_config: BinarizationConfig):
        """Update GUI from new config values"""
        self._core_config = new_config
        self.threshold_offset.set(new_config.threshold_offset)
        self.frame_step.set(new_config.frame_step)
        self.percentage_frames_evaluated.set(new_config.percentage_frames_evaluated)
        self.bin_factor.set(new_config.bin_factor)
        self.neighbor_island_fraction.set(new_config.neighbor_island_fraction)
        self.minimum_island_size.set(new_config.minimum_island_size)
        self.enable_physical_units.set(new_config.enable_physical_units)
        self.invert_binarization.set(new_config.invert_binarization)

@dataclass
class SegmentationConfigGUI:
    """Auto-generated GUI wrapper for SegmentationConfig"""
    _core_config: SegmentationConfig = field(default_factory=SegmentationConfig)

    method: tk.StringVar = field(init=False)
    model_plugin: tk.StringVar = field(init=False)
    adaptive_block_size: tk.IntVar = field(init=False)
    adaptive_c: tk.DoubleVar = field(init=False)
    invert_mask: tk.BooleanVar = field(init=False)
    canny_low: tk.IntVar = field(init=False)
    canny_high: tk.IntVar = field(init=False)
    blur_kernel: tk.IntVar = field(init=False)
    open_kernel: tk.IntVar = field(init=False)
    open_iterations: tk.IntVar = field(init=False)
    close_kernel: tk.IntVar = field(init=False)
    close_iterations: tk.IntVar = field(init=False)
    minimum_segment_area: tk.IntVar = field(init=False)
    deformation_method: tk.StringVar = field(init=False)
    deformation_window: tk.IntVar = field(init=False)
    strain_type: tk.StringVar = field(init=False)
    crack_invert_mask: tk.BooleanVar = field(init=False)
    frame_step: tk.IntVar = field(init=False)
    percentage_frames_evaluated: tk.DoubleVar = field(init=False)

    def __post_init__(self):
        self.method = tk.StringVar(value=self._core_config.method)
        self.model_plugin = tk.StringVar(value=self._core_config.model_plugin)
        self.adaptive_block_size = tk.IntVar(value=self._core_config.adaptive_block_size)
        self.adaptive_c = tk.DoubleVar(value=self._core_config.adaptive_c)
        self.invert_mask = tk.BooleanVar(value=self._core_config.invert_mask)
        self.canny_low = tk.IntVar(value=self._core_config.canny_low)
        self.canny_high = tk.IntVar(value=self._core_config.canny_high)
        self.blur_kernel = tk.IntVar(value=self._core_config.blur_kernel)
        self.open_kernel = tk.IntVar(value=self._core_config.open_kernel)
        self.open_iterations = tk.IntVar(value=self._core_config.open_iterations)
        self.close_kernel = tk.IntVar(value=self._core_config.close_kernel)
        self.close_iterations = tk.IntVar(value=self._core_config.close_iterations)
        self.minimum_segment_area = tk.IntVar(value=self._core_config.minimum_segment_area)
        self.deformation_method = tk.StringVar(value=self._core_config.deformation_method)
        self.deformation_window = tk.IntVar(value=self._core_config.deformation_window)
        self.strain_type = tk.StringVar(value=self._core_config.strain_type)
        self.crack_invert_mask = tk.BooleanVar(value=self._core_config.crack_invert_mask)
        self.frame_step = tk.IntVar(value=self._core_config.frame_step)
        self.percentage_frames_evaluated = tk.DoubleVar(value=self._core_config.percentage_frames_evaluated)

    @property
    def config(self) -> SegmentationConfig:
        """Get current config from GUI values"""
        return SegmentationConfig(
            method=self.method.get(),
            model_plugin=self.model_plugin.get(),
            adaptive_block_size=self.adaptive_block_size.get(),
            adaptive_c=self.adaptive_c.get(),
            invert_mask=self.invert_mask.get(),
            canny_low=self.canny_low.get(),
            canny_high=self.canny_high.get(),
            blur_kernel=self.blur_kernel.get(),
            open_kernel=self.open_kernel.get(),
            open_iterations=self.open_iterations.get(),
            close_kernel=self.close_kernel.get(),
            close_iterations=self.close_iterations.get(),
            minimum_segment_area=self.minimum_segment_area.get(),
            deformation_method=self.deformation_method.get(),
            deformation_window=self.deformation_window.get(),
            strain_type=self.strain_type.get(),
            crack_invert_mask=self.crack_invert_mask.get(),
            frame_step=self.frame_step.get(),
            percentage_frames_evaluated=self.percentage_frames_evaluated.get(),
        )

    def update_gui(self, new_config: SegmentationConfig):
        """Update GUI from new config values"""
        self._core_config = new_config
        self.method.set(new_config.method)
        self.model_plugin.set(new_config.model_plugin)
        self.adaptive_block_size.set(new_config.adaptive_block_size)
        self.adaptive_c.set(new_config.adaptive_c)
        self.invert_mask.set(new_config.invert_mask)
        self.canny_low.set(new_config.canny_low)
        self.canny_high.set(new_config.canny_high)
        self.blur_kernel.set(new_config.blur_kernel)
        self.open_kernel.set(new_config.open_kernel)
        self.open_iterations.set(new_config.open_iterations)
        self.close_kernel.set(new_config.close_kernel)
        self.close_iterations.set(new_config.close_iterations)
        self.minimum_segment_area.set(new_config.minimum_segment_area)
        self.deformation_method.set(new_config.deformation_method)
        self.deformation_window.set(new_config.deformation_window)
        self.strain_type.set(new_config.strain_type)
        self.crack_invert_mask.set(new_config.crack_invert_mask)
        self.frame_step.set(new_config.frame_step)
        self.percentage_frames_evaluated.set(new_config.percentage_frames_evaluated)

@dataclass
class OpticalFlowConfigGUI:
    """Auto-generated GUI wrapper for OpticalFlowConfig"""
    _core_config: OpticalFlowConfig = field(default_factory=OpticalFlowConfig)

    frame_step: tk.IntVar = field(init=False)
    win_size: tk.IntVar = field(init=False)
    downsample: tk.IntVar = field(init=False)
    percentage_frames_evaluated: tk.DoubleVar = field(init=False)

    def __post_init__(self):
        self.frame_step = tk.IntVar(value=self._core_config.frame_step)
        self.win_size = tk.IntVar(value=self._core_config.win_size)
        self.downsample = tk.IntVar(value=self._core_config.downsample)
        self.percentage_frames_evaluated = tk.DoubleVar(value=self._core_config.percentage_frames_evaluated)

    @property
    def config(self) -> OpticalFlowConfig:
        """Get current config from GUI values"""
        return OpticalFlowConfig(
            frame_step=self.frame_step.get(),
            win_size=self.win_size.get(),
            downsample=self.downsample.get(),
            percentage_frames_evaluated=self.percentage_frames_evaluated.get(),
        )

    def update_gui(self, new_config: OpticalFlowConfig):
        """Update GUI from new config values"""
        self._core_config = new_config
        self.frame_step.set(new_config.frame_step)
        self.win_size.set(new_config.win_size)
        self.downsample.set(new_config.downsample)
        self.percentage_frames_evaluated.set(new_config.percentage_frames_evaluated)

@dataclass
class IntensityDistributionConfigGUI:
    """Auto-generated GUI wrapper for IntensityDistributionConfig"""
    _core_config: IntensityDistributionConfig = field(default_factory=IntensityDistributionConfig)

    bin_size: tk.IntVar = field(init=False)
    frame_step: tk.IntVar = field(init=False)
    noise_threshold: tk.DoubleVar = field(init=False)
    percentage_frames_evaluated: tk.DoubleVar = field(init=False)

    def __post_init__(self):
        self.bin_size = tk.IntVar(value=self._core_config.bin_size)
        self.frame_step = tk.IntVar(value=self._core_config.frame_step)
        self.noise_threshold = tk.DoubleVar(value=self._core_config.noise_threshold)
        self.percentage_frames_evaluated = tk.DoubleVar(value=self._core_config.percentage_frames_evaluated)

    @property
    def config(self) -> IntensityDistributionConfig:
        """Get current config from GUI values"""
        return IntensityDistributionConfig(
            bin_size=self.bin_size.get(),
            frame_step=self.frame_step.get(),
            noise_threshold=self.noise_threshold.get(),
            percentage_frames_evaluated=self.percentage_frames_evaluated.get(),
        )

    def update_gui(self, new_config: IntensityDistributionConfig):
        """Update GUI from new config values"""
        self._core_config = new_config
        self.bin_size.set(new_config.bin_size)
        self.frame_step.set(new_config.frame_step)
        self.noise_threshold.set(new_config.noise_threshold)
        self.percentage_frames_evaluated.set(new_config.percentage_frames_evaluated)

@dataclass
class PreviewConfigGUI:
    """Auto-generated GUI wrapper for PreviewConfig"""
    _core_config: PreviewConfig = field(default_factory=PreviewConfig)

    sample_file: tk.StringVar = field(init=False)
    enable_live_preview: tk.BooleanVar = field(init=False)
    _sample_file: tk.StringVar = field(init=False)
    _sample_preview: np.ndarray = None
    preview_frame_number: tk.IntVar = field(init=False)

    def __post_init__(self):
        self.sample_file = tk.StringVar(value=self._core_config.sample_file)
        self.enable_live_preview = tk.BooleanVar(value=self._core_config.enable_live_preview)
        self._sample_file = tk.StringVar(value=self._core_config._sample_file)
        self._sample_preview: np.ndarray = None
        self.preview_frame_number = tk.IntVar(value=self._core_config.preview_frame_number)
    
    @property
    def sample_preview(self) -> np.ndarray:
        if self._sample_preview is None or self._sample_file.get() != self.sample_file.get():
            filepath = self.sample_file.get()
            if filepath.endswith(('.avi', '.mp4')):
                frames = []
                container = av.open(filepath)
                for frame in container.decode(video=0):
                    frames.append(frame.to_ndarray(format='gray'))
                file = np.array(frames)
                file = np.expand_dims(file, axis = 3) if len(file.shape) == 3 else file
            elif filepath.endswith(('.tif', '.tiff')):
                file = iio.imread(filepath)
                file = np.expand_dims(file, axis = 3) if len(file.shape) == 3 else file
                if file.shape[3] != min(file.shape):
                    file = np.swapaxes(np.swapaxes(file, 1, 2), 2, 3)
            elif filepath.endswith('.nd2'):
                with nd2.ND2File(filepath) as ndfile:
                    if (len(ndfile.sizes) < 5 and (not 'Z' in ndfile.sizes) and 
                        'T' in ndfile.sizes and len(ndfile.shape) > 2 and ndfile.sizes['T'] > 5):
                        file = ndfile.asarray()
                        file = np.expand_dims(file, axis = 1) if len(file.shape) == 3 else file
                        file = np.swapaxes(np.swapaxes(file, 1, 2), 2, 3)
            else:
                file = np.ones((3, 256, 256, 1))
            self._sample_preview = file
            self._sample_file.set(filepath)
        return self._sample_preview

    @property
    def config(self) -> PreviewConfig:
        """Get current config from GUI values"""
        return PreviewConfig(
            sample_file=self.sample_file.get(),
            enable_live_preview=self.enable_live_preview.get(),
            _sample_file=self._sample_file.get(),
            _sample_preview=self._sample_preview,
            preview_frame_number=self.preview_frame_number.get(),
        )

    def update_gui(self, new_config: PreviewConfig):
        """Update GUI from new config values"""
        self._core_config = new_config
        self.sample_file.set(new_config.sample_file)
        self.enable_live_preview.set(new_config.enable_live_preview)
        self._sample_file.set(new_config._sample_file)
        self._sample_preview = None
        self.preview_frame_number.set(new_config.preview_frame_number)

@dataclass
class AggregationConfigGUI:
    """Auto-generated GUI wrapper for AggregationConfig"""
    _core_config: AggregationConfig = field(default_factory=AggregationConfig)

    output_location: tk.StringVar = field(init=False)
    generate_single_barcode: tk.BooleanVar = field(init=False)
    generate_comparison_barcodes: tk.BooleanVar = field(init=False)
    separate_channels: tk.BooleanVar = field(init=False)
    sort_parameter: tk.StringVar = field(init=False)
    csv_paths_list: List[str] = field(default_factory=list)
    metrics_list: List[bool] = field(default_factory=list)

    def __post_init__(self):
        self.output_location = tk.StringVar(value=self._core_config.output_location)
        self.generate_single_barcode = tk.BooleanVar(value=self._core_config.generate_single_barcode)
        self.generate_comparison_barcodes = tk.BooleanVar(value=self._core_config.generate_comparison_barcodes)
        self.separate_channels = tk.BooleanVar(value=self._core_config.separate_channels)
        self.sort_parameter = tk.StringVar(value=self._core_config.sort_parameter)
        self.csv_paths_list = list(self._core_config.csv_paths_list)
        self.metrics_list = list(self._core_config.metrics_list)

    @property
    def config(self) -> AggregationConfig:
        """Get current config from GUI values"""
        return AggregationConfig(
            output_location=self.output_location.get(),
            generate_single_barcode=self.generate_single_barcode.get(),
            generate_comparison_barcodes=self.generate_comparison_barcodes.get(),
            separate_channels=self.separate_channels.get(),
            sort_parameter=self.sort_parameter.get(),
            csv_paths_list=self.csv_paths_list,
            metrics_list=self.metrics_list,
        )

    def update_gui(self, new_config: AggregationConfig):
        """Update GUI from new config values"""
        self._core_config = new_config
        self.output_location.set(new_config.output_location)
        self.generate_single_barcode.set(new_config.generate_single_barcode)
        self.generate_comparison_barcodes.set(new_config.generate_comparison_barcodes)
        self.separate_channels.set(new_config.separate_channels)
        self.sort_parameter.set(new_config.sort_parameter)
        self.csv_paths_list.set(new_config.csv_paths_list)
        self.metrics_list.set(new_config.metrics_list)

@dataclass
class ComparisonConfigGUI:
    """Auto-generated GUI wrapper for ComparisonConfig"""
    _core_config: ComparisonConfig = field(default_factory=ComparisonConfig)

    csv_location: tk.StringVar = field(init=False)
    first_comparison_metric: tk.StringVar = field(init=False)
    second_comparison_metric: tk.StringVar = field(init=False)
    output_location: tk.StringVar = field(init=False)

    def __post_init__(self):
        self.csv_location = tk.StringVar(value=self._core_config.csv_location)
        self.first_comparison_metric = tk.StringVar(value=self._core_config.first_comparison_metric)
        self.second_comparison_metric = tk.StringVar(value=self._core_config.second_comparison_metric)
        self.output_location = tk.StringVar(value=self._core_config.output_location)

    @property
    def config(self) -> ComparisonConfig:
        """Get current config from GUI values"""
        return ComparisonConfig(
            csv_location=self.csv_location.get(),
            first_comparison_metric=self.first_comparison_metric.get(),
            second_comparison_metric=self.second_comparison_metric.get(),
            output_location=self.output_location.get(),
        )

    def update_gui(self, new_config: ComparisonConfig):
        """Update GUI from new config values"""
        self._core_config = new_config
        self.csv_location.set(new_config.csv_location)
        self.first_comparison_metric.set(new_config.first_comparison_metric)
        self.second_comparison_metric.set(new_config.second_comparison_metric)
        self.output_location.set(new_config.output_location)

@dataclass
class ModuleConfigGUI:
    """Auto-generated GUI wrapper for ModuleConfig"""
    _core_config: ModuleConfig = field(default_factory=ModuleConfig)

    image_binarization: tk.BooleanVar = field(init=False)
    edge_segmentation: tk.BooleanVar = field(init=False)
    optical_flow: tk.BooleanVar = field(init=False)
    intensity_distribution: tk.BooleanVar = field(init=False)

    def __post_init__(self):
        self.image_binarization = tk.BooleanVar(value=self._core_config.image_binarization)
        self.edge_segmentation = tk.BooleanVar(value=self._core_config.edge_segmentation)
        self.optical_flow = tk.BooleanVar(value=self._core_config.optical_flow)
        self.intensity_distribution = tk.BooleanVar(value=self._core_config.intensity_distribution)

    @property
    def config(self) -> ModuleConfig:
        """Get current config from GUI values"""
        return ModuleConfig(
            image_binarization=self.image_binarization.get(),
            edge_segmentation=self.edge_segmentation.get(),
            optical_flow=self.optical_flow.get(),
            intensity_distribution=self.intensity_distribution.get(),
        )

    def update_gui(self, new_config: ModuleConfig):
        """Update GUI from new config values"""
        self._core_config = new_config
        self.image_binarization.set(new_config.image_binarization)
        self.edge_segmentation.set(new_config.edge_segmentation)
        self.optical_flow.set(new_config.optical_flow)
        self.intensity_distribution.set(new_config.intensity_distribution)

@dataclass
class VisualizationConfigGUI:
    """Auto-generated GUI wrapper for VisualizationConfig"""
    _core_config: VisualizationConfig = field(default_factory=VisualizationConfig)

    file_path: tk.StringVar = field(init=False)
    rds_type: tk.StringVar = field(init=False)
    scale: tk.DoubleVar = field(init=False)
    preview_frame_number: tk.IntVar = field(init=False)
    video_framerate: tk.DoubleVar = field(init=False)
    _file_path: tk.StringVar = field(init=False)
    _frames: List[np.ndarray] = field(default_factory=list)
    _indices: List[int] = field(default_factory=list)

    def __post_init__(self):
        self.file_path = tk.StringVar(value=self._core_config.file_path)
        self.rds_type = tk.StringVar(value=self._core_config.rds_type)
        self.scale = tk.DoubleVar(value=self._core_config.scale)
        self.preview_frame_number = tk.IntVar(value=self._core_config.preview_frame_number)
        self.video_framerate = tk.DoubleVar(value=self._core_config.video_framerate)
        self._file_path = tk.StringVar(value=self._core_config._file_path)
        self._frames = list(self._core_config._frames)
        self._indices = list(self._core_config._indices)

    def append(self, major_arr, minor_arr):
        if not isinstance(major_arr, np.ndarray):
            major_arr = np.expand_dims(minor_arr, axis = 0)
        else:
            minor_arr = np.expand_dims(minor_arr, axis = 0)
            major_arr = np.append(major_arr, minor_arr, axis=0)
        return major_arr
        
    def read_of_rds(self, path: str) -> tuple[np.ndarray, list]:
        '''
        Reads flow fields from a BARCODE-generated CSV file into two arrays with dimension (num_frames, width, height)
        and one array with the index of the flow fields
        '''
        flow_field_x = None
        flow_field_y = None
        flow_field_indices = []
        with open(path, 'r') as file:
            csvreader = csv.reader(file)
            x_flag = True
            x_field = None
            y_field = None
            for row in csvreader:
                if len(row) == 0:
                    continue
                elif len(row) == 1:
                    if str(row[0]).startswith('X'):
                        x_flag = True
                    if str(row[0]).startswith('Y'):
                        x_flag = False
                    if str(row[0]).startswith('Flow Field'):
                        flow_idx = int(str(row[0]).split('-')[0].split(' ')[2][1:])
                        flow_idx2 = int(str(row[0]).split('-')[1][:-1])
                        # print(flow_idx, flow_idx2)
                        flow_field_indices.append([flow_idx, flow_idx2])
                        x_flag = True
                        if isinstance(x_field, np.ndarray):
                            flow_field_x = self.append(flow_field_x, x_field)
                            flow_field_y = self.append(flow_field_y, y_field)
                            x_field = None
                            y_field = None
                else:
                    row = np.array(np.float64(row))
                    if x_flag:
                        x_field = np.vstack((x_field, row)) if isinstance(x_field, np.ndarray) else row
                    else:
                        y_field = np.vstack((y_field, row)) if isinstance(y_field, np.ndarray) else row
                            
            if isinstance(x_field, np.ndarray):
                flow_field_x = self.append(flow_field_x, x_field)
                flow_field_y = self.append(flow_field_y, y_field)
                x_field = None
                y_field = None
        flow_field_x = np.expand_dims(flow_field_x, axis=3)
        flow_field_y = np.expand_dims(flow_field_y, axis=3)
        flow_field = np.append(flow_field_x, flow_field_y, axis=3)
        return flow_field, flow_field_indices

    def read_ib_rds(self, path: str) -> tuple[np.ndarray, list]:
        bin_frame_indices = []
        bin_frames = None
        with open(path, 'r') as file:
            bin_frame = None
            csvreader = csv.reader(file)
            for row in csvreader:
                if len(row) == 0:
                    continue
                if len(row) == 1:
                    bin_frame_indices.append(int(row[0].removeprefix("Frame ")))
                    if isinstance(bin_frame, np.ndarray):
                        bin_frames = self.append(bin_frames, bin_frame)
                        bin_frame=None
                else:
                    row = np.array(np.float64(row))
                    row = row.astype(int)
                    if not isinstance(bin_frame, np.ndarray):
                        bin_frame = row
                    else:
                        bin_frame = np.vstack((bin_frame, row))
            if isinstance(bin_frame, np.ndarray):
                bin_frames = self.append(bin_frames, bin_frame)
                bin_frame=None
        return bin_frames, bin_frame_indices

    def read_field_rds(self, path: str) -> tuple[np.ndarray, list]:
        field_indices = []
        fields = []
        with open(path, 'r') as file:
            field_frame = None
            csvreader = csv.reader(file)
            for row in csvreader:
                if len(row) == 0:
                    continue
                elif len(row) == 1:
                    if str(row[0]).startswith('Flow Field'):
                        flow_idx = int(str(row[0]).split('-')[0].split(' ')[2][1:])
                        flow_idx2 = int(str(row[0]).split('-')[1][:-1])
                        # print(flow_idx, flow_idx2)
                        field_indices.append([flow_idx, flow_idx2])
                    if isinstance(field_frame, np.ndarray):
                        fields = self.append(fields, field_frame)
                        field_frame = None
                else:
                    row = np.array(np.float64(row))
                    if not isinstance(field_frame, np.ndarray):
                        field_frame = row
                    else:
                        field_frame = np.vstack((field_frame, row))
            if isinstance(field_frame, np.ndarray):
                fields = self.append(fields, field_frame)
                field_frame =None
        return fields, field_indices

    def read_id_rds(self, path: str) -> tuple[list, np.ndarray]:
        frame_nums = []
        frame_dists = []
        with open(path, 'r', newline = '\n') as file:
            csvreader = csv.reader(file)
            for row in csvreader:
                if len(row) == 0:
                    continue
                if len(row) == 1 and 'Frame' in row[0]:
                    frame_nums.append(int(row[0].removeprefix('Frame ')))
                    intensity_values = np.array(next(csvreader))
                    intensity_values = np.reshape(intensity_values, (intensity_values.shape[0], 1))
                    
                    intensity_counts = np.array(next(csvreader))
                    intensity_counts = np.reshape(intensity_counts, (intensity_counts.shape[0], 1))
                    
                    dist = np.append(intensity_values, intensity_counts, axis=1).astype(float)
                    frame_dists.append(dist)
        return frame_dists, np.array(frame_nums)

    def read_correlation_rds(self, path: str) -> tuple[list, np.ndarray]:
        frame_nums = []
        frame_dists = []
        correlation_type = 'Structural' if 'StructuralImageAutocorrelation' in path else 'Velocity'
        def get_frames(frame_str):
            if correlation_type == 'Structural':
                return int(frame_str.removeprefix('Frame ').removesuffix(f' {correlation_type} Correlation'))
            elif correlation_type == 'Velocity':
                return int(frame_str.split('-')[0].removeprefix('Flow Field '))

        with open(path, 'r', newline = '\n') as file:
            csvreader = csv.reader(file)
            for row in csvreader:
                if len(row) == 0:
                    continue
                if len(row) == 1:
                    frame_nums.append(get_frames(row[0]))
                    radius = np.array(next(csvreader))[1:]
                    radius = np.reshape(radius, (radius.shape[0], 1))
                    
                    correlations = np.array(next(csvreader))[1:]
                    correlations = np.reshape(correlations, (correlations.shape[0], 1))
                    
                    dist = np.append(radius, correlations, axis=1).astype(float)
                    frame_dists.append(dist)
        return frame_dists, np.array(frame_nums)

    @property
    def frames(self) -> list | np.ndarray:
        if len(self._frames) == 0 or self.file_path.get() != self._file_path.get():
            frame_nums = []
            frame_dists = []
            filepath = self.file_path.get()
            if not (os.path.exists(filepath) and filepath.endswith('.csv')):
                return [None] * 3
            rds_map = {
                'BinarizationData': ('Image_Binarization', self.read_ib_rds),
                'OpticalFlow': ('Optical_Flow', self.read_of_rds),
                'IntensityDistribution': ('Intensity_Distribution', self.read_id_rds),
                'StructuralImageAutocorrelation': ('Spatial_Autocorrelation', self.read_correlation_rds),
                'VelocityCorrelation': ('Velocity_Correlation', self.read_correlation_rds), 
                'Divergence': ('Vector_Fields', self.read_field_rds),
                'Curl': ('Vector_Fields', self.read_field_rds),
            }
            for key in rds_map.keys():
                if key in filepath:
                    branch_name, rds_function = rds_map[key]
                    self.rds_type.set(branch_name)
                    rds_results = rds_function(filepath)
                    self._frames = rds_results[0]
                    self._indices = rds_results[1]
                    self._file_path.set(filepath)
        return self._frames

    @property
    def indices(self) -> np.ndarray:
        if len(self._indices) == 0 or self.file_path.get() != self._file_path.get():
            self.frames()
        return self._indices

    @property
    def config(self) -> VisualizationConfig:
        """Get current config from GUI values"""
        return VisualizationConfig(
            file_path=self.file_path.get(),
            rds_type=self.rds_type.get(),
            scale=self.scale.get(),
            preview_frame_number=self.preview_frame_number.get(),
            video_framerate=self.video_framerate.get(),
            _file_path=self._file_path.get(),
            _frames=self._frames,
            _indices=self._indices,
        )

    def update_gui(self, new_config: VisualizationConfig):
        """Update GUI from new config values"""
        self._core_config = new_config
        self.file_path.set(new_config.file_path)
        self.rds_type.set(new_config.rds_type)
        self.scale.set(new_config.scale)
        self.preview_frame_number.set(new_config.preview_frame_number)
        self.video_framerate.set(new_config.video_framerate)
        self._file_path.set(new_config._file_path)
        self._frames = None
        self._indices.set(new_config._indices)

@dataclass
class BarcodeConfigGUI:
    """Auto-generated master GUI configuration"""
    _core_config: BarcodeConfig = field(default_factory=BarcodeConfig)

    channels: ChannelConfigGUI = field(init=False)
    image_binarization_parameters: BinarizationConfigGUI = field(init=False)
    segmentation_parameters: SegmentationConfigGUI = field(init=False)
    intensity_distribution_parameters: IntensityDistributionConfigGUI = field(init=False)
    modules: ModuleConfigGUI = field(init=False)
    optical_flow_parameters: OpticalFlowConfigGUI = field(init=False)
    reader: ReaderConfigGUI = field(init=False)
    writer: WriterConfigGUI = field(init=False)

    def __post_init__(self):
        self.channels = ChannelConfigGUI(self._core_config.channels)
        self.image_binarization_parameters = BinarizationConfigGUI(self._core_config.image_binarization_parameters)
        self.segmentation_parameters = SegmentationConfigGUI(self._core_config.segmentation_parameters)
        self.intensity_distribution_parameters = IntensityDistributionConfigGUI(self._core_config.intensity_distribution_parameters)
        self.modules = ModuleConfigGUI(self._core_config.modules)
        self.optical_flow_parameters = OpticalFlowConfigGUI(self._core_config.optical_flow_parameters)
        self.reader = ReaderConfigGUI(self._core_config.reader)
        self.writer = WriterConfigGUI(self._core_config.writer)

    @property
    def config(self) -> BarcodeConfig:
        """Get current config from all GUI values"""
        return BarcodeConfig(
            channels=self.channels.config,
            image_binarization_parameters=self.image_binarization_parameters.config,
            segmentation_parameters=self.segmentation_parameters.config,
            intensity_distribution_parameters=self.intensity_distribution_parameters.config,
            modules=self.modules.config,
            optical_flow_parameters=self.optical_flow_parameters.config,
            reader=self.reader.config,
            writer=self.writer.config,
        )
@dataclass
class AnalysisConfigGUI:
    """Auto-generated master GUI configuration"""
    _core_config: AnalysisConfig = field(default_factory=AnalysisConfig)

    aggregation: AggregationConfigGUI = field(init=False)
    comparison: ComparisonConfigGUI = field(init=False)
    visualization: VisualizationConfigGUI = field(init=False)

    def __post_init__(self):
        self.aggregation = AggregationConfigGUI(self._core_config.aggregation)
        self.comparison = ComparisonConfigGUI(self._core_config.comparison)
        self.visualization = VisualizationConfigGUI(self._core_config.visualization)

    @property
    def config(self) -> AnalysisConfig:
        """Get current config from all GUI values"""
        return AnalysisConfig(
            aggregation=self.aggregation.config,
            comparison=self.comparison.config,
            visualization=self.visualization.config,
        )